In [2]:
import pandas as pd
from datetime import datetime
from dateutil import tz
import csv

In [4]:
#url = https://www.kaggle.com/unanimad/reddit-rwallstreetbets/tasks
csvfile = '../Resources/r_wallstreetbets_posts.csv'
data = pd.read_csv(csvfile)
data.head()

/Users/tiffanyharris/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,id,title,score,author,author_flair_text,removed_by,total_awards_received,awarders,created_utc,full_link,num_comments,over_18
0,ll0n5k,Whats going on with PLTR?,1,Zaccko98,NaN,moderator,0.0,[],1613469192,https://www.reddit.com/r/wallstreetbets/commen...,2,False
1,ll0n4p,"Need explanations on Level 2 data for GME, why...",1,toutoucnc,210115:1:1,moderator,0.0,[],1613469189,https://www.reddit.com/r/wallstreetbets/commen...,2,False
2,ll0my2,XRT is being used as a laundry short machine,1,thabat,NaN,moderator,0.0,[],1613469166,https://www.reddit.com/r/wallstreetbets/commen...,2,False
3,ll0mxr,Airlines?,1,AsianTwink_,NaN,moderator,0.0,[],1613469165,https://www.reddit.com/r/wallstreetbets/commen...,2,False
4,ll0mx4,Buy TRXC ðŸš€,1,Oneverystreet8,NaN,moderator,0.0,[],1613469164,https://www.reddit.com/r/wallstreetbets/commen...,2,False

In [5]:
data.columns

Index(['id', 'title', 'score', 'author', 'author_flair_text', 'removed_by',
       'total_awards_received', 'awarders', 'created_utc', 'full_link',
       'num_comments', 'over_18'],
      dtype='object')

In [13]:
print(datetime.fromtimestamp(int("1611817696")).strftime('%Y-%m-%d %H:%M:%S'))

2021-01-28 01:08:16

In [14]:
import json

In [15]:
jsonfile = '../Resources/wsbData.json'

In [18]:
json_pd = pd.read_json(jsonfile, lines=True)

In [19]:
json_pd.head()

,body,score_hidden,archived,name,author,downs,created_utc,subreddit_id,link_id,parent_id,score,retrieved_on,controversiality,gilded,id,subreddit,ups,author_flair_text,author_flair_css_class,distinguished
0,[deleted],0.0,1.0,t1_chi0ufo,[deleted],0.0,1400098596,t5_2th52,t3_25jeio,t1_chhzelx,0,1.433797e+09,0,0,chi0ufo,wallstreetbets,0.0,NaN,NaN,NaN
1,"Lol. Yeah, Welp.",0.0,0.0,t1_cl52foo,JamesAQuintero,0.0,1412888184,t5_2th52,t3_2ikdc5,t1_cl47s92,1,1.426605e+09,0,0,cl52foo,wallstreetbets,1.0,NaN,NaN,NaN
2,[deleted],0.0,1.0,t1_ch5wdhy,[deleted],0.0,1398860210,t5_2th52,t3_24a77l,t1_ch5diku,1,1.433588e+09,0,0,ch5wdhy,wallstreetbets,1.0,NaN,NaN,NaN
3,Crypto miners is not a significant enough mark...,0.0,1.0,t1_cfj9fzo,Zytran,0.0,1392824901,t5_2th52,t3_1y409u,t3_1y409u,1,1.432466e+09,0,0,cfj9fzo,wallstreetbets,1.0,NaN,NaN,NaN
4,Sold a covered call at 560. I almost wish it d...,0.0,1.0,t1_ch0jw88,FarmPal,0.0,1398311440,t5_2th52,t3_23sjde,t3_23sjde,1,1.433495e+09,0,0,ch0jw88,wallstreetbets,1.0,NaN,NaN,NaN

In [20]:
len(json_pd)

2979131

In [24]:
json_pd.sort_values('created_utc', ascending=False)

,body,score_hidden,archived,name,author,downs,created_utc,subreddit_id,link_id,parent_id,score,retrieved_on,controversiality,gilded,id,subreddit,ups,author_flair_text,author_flair_css_class,distinguished
1580798,Yes I also hate jokes,NaN,0.0,NaN,cheezus_lives,NaN,1541030397,t5_2th52,t3_9t0n1c,t1_e8teeuq,4,1.541688e+09,0,0,e8tki1u,wallstreetbets,NaN,NaN,NaN,NaN
1395369,[deleted],NaN,0.0,NaN,[deleted],NaN,1541030376,t5_2th52,t3_9soy0s,t1_e8s9c6p,1,1.541688e+09,0,0,e8tkhax,wallstreetbets,NaN,NaN,NaN,NaN
1680110,Only if it is in its original packaging.,NaN,0.0,NaN,pourGasOnYou,NaN,1541030373,t5_2th52,t3_9t2keu,t1_e8thbhg,3,1.541688e+09,0,0,e8tkh6w,wallstreetbets,NaN,NaN,NaN,NaN
1874639,"No idea. I get emails for every trade though, ...",NaN,0.0,NaN,Saleenm99,NaN,1541030373,t5_2th52,t3_9t2uvt,t1_e8t9mu3,1,1.541688e+09,0,0,e8tkh6j,wallstreetbets,NaN,NaN,NaN,NaN
2263950,"LOL true WSB. He hopes it maintains, he loses...",NaN,0.0,NaN,Gahvynn,NaN,1541030357,t5_2th52,t3_9t2wlw,t1_e8tjs0s,5,1.541688e+09,0,0,e8tkgll,wallstreetbets,NaN,a decent lad,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514977,"GMCR falls, GOOG falls *slightly*, GRPN will g...",0.0,1.0,t1_c4b2egm,Workahol,0.0,1334170031,t5_2th52,t3_s4jw1,t3_s4jw1,6,1.428700e+09,0,0,c4b2egm,wallstreetbets,6.0,NaN,NaN,NaN
489782,"straddle, call, straddle, put, put, put, strad...",0.0,1.0,t1_c4b1rmm,entsportsjunkie,0.0,1334167351,t5_2th52,t3_s4jw1,t3_s4jw1,1,1.428700e+09,0,0,c4b1rmm,wallstreetbets,1.0,NaN,NaN,NaN
502823,INTC is on 4/17,0.0,1.0,t1_c4b1fpf,glorysk87,0.0,1334165948,t5_2th52,t3_s4jw1,t3_s4jw1,2,1.428700e+09,0,0,c4b1fpf,wallstreetbets,2.0,NaN,NaN,NaN
529261,[deleted],0.0,1.0,t1_c4b127p,[deleted],0.0,1334164336,t5_2th52,t3_s4jw1,t3_s4jw1,1,1.428700e+09,0,0,c4b127p,wallstreetbets,1.0,NaN,NaN,NaN
563183,This is a fantastic idea! I'll toss mine up in...,0.0,1.0,t1_c4b0pvu,secondhandsondek,0.0,1334162803,t5_2th52,t3_s4jw1,t3_s4jw1,2,1.428700e+09,0,0,c4b0pvu,wallstreetbets,2.0,NaN,NaN,NaN

In [23]:
print(datetime.fromtimestamp(int("1334162803")).strftime('%Y-%m-%d %H:%M:%S'))

2012-04-11 11:46:43

In [25]:
print(datetime.fromtimestamp(int("1541030397")).strftime('%Y-%m-%d %H:%M:%S'))

2018-10-31 18:59:57